name: webbudget

services:
  postgres:
    container_name: wb-database
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=webbudget
      - POSTGRES_USER=sa_webbudget
      - POSTGRES_PASSWORD=sa_webbudget
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    volumes:
      - data-postgres:/var/lib/postgresql/data
    networks:
      - default

  maildev:
    container_name: wb-maildev
    image: soulteary/maildev:latest
    ports:
      - "1080:1080"
      - "1025:1025"
    environment:
      - MAILDEV_INCOMING_USER=maildev
      - MAILDEV_INCOMING_PASS=maildev
    networks:
      - default

volumes:
  data-postgres:
    driver: local

networks:
  default:
    driver: bridge
