name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Detekt
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: current
          arguments: detekt --no-daemon

      - name: Test
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: current
          arguments: test --no-daemon -x detekt

      - name: Build
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: current
          arguments: build --no-daemon -x test -x detekt
